# require('browsernizr/test/css/transitions')
require('browsernizr/test/touchevents')
# require('browsernizr/test/css/transforms3d')
# require('browsernizr/test/css/transforms')
# require('browsernizr/test/css/mediaqueries')
# require('browsernizr/test/css/opacity')
# require('browsernizr/test/css/animations')
# require('browsernizr/test/svg')
# require('browsernizr/test/css/backgroundblendmode')
# require('browsernizr/test/canvas')

module.exports = require('browsernizr')